# use `cargo +nightly fmt` to format
unstable_features = true

binop_separator = "Back"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
combine_control_expr = false
chain_width = 45

wrap_comments = true
comment_width = 80

format_macro_bodies = true
format_macro_matchers = true
format_strings = true

group_imports = "StdExternalCrate"
imports_granularity = "Module"

empty_item_single_line = false

match_block_trailing_comma = true

max_width = 80